<?php

/**
 * This file is part of slick/i18n package
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

return [
    ["code" => "af",        "description" => "Afrikaans"],
    ["code" => "af-ZA",     "description" => "Afrikaans (South Africa)"],
    ["code" => "ar",        "description" => "Arabic"],
    ["code" => "ar-AE",     "description" => "Arabic (U.A.E.)"],
    ["code" => "ar-BH",     "description" => "Arabic (Bahrain)"],
    ["code" => "ar-DZ",     "description" => "Arabic (Algeria)"],
    ["code" => "ar-EG",     "description" => "Arabic (Egypt)"],
    ["code" => "ar-IQ",     "description" => "Arabic (Iraq)"],
    ["code" => "ar-JO",     "description" => "Arabic (Jordan)"],
    ["code" => "ar-KW",     "description" => "Arabic (Kuwait)"],
    ["code" => "ar-LB",     "description" => "Arabic (Lebanon)"],
    ["code" => "ar-LY",     "description" => "Arabic (Libya)"],
    ["code" => "ar-MA",     "description" => "Arabic (Morocco)"],
    ["code" => "ar-OM",     "description" => "Arabic (Oman)"],
    ["code" => "ar-QA",     "description" => "Arabic (Qatar)"],
    ["code" => "ar-SA",     "description" => "Arabic (Saudi Arabia)"],
    ["code" => "ar-SY",     "description" => "Arabic (Syria)"],
    ["code" => "ar-TN",     "description" => "Arabic (Tunisia)"],
    ["code" => "ar-YE",     "description" => "Arabic (Yemen)"],
    ["code" => "az",        "description" => "Azeri (Latin)"],
    ["code" => "az-AZ",     "description" => "Azeri (Latin) (Azerbaijan)"],
    ["code" => "az-AZ",     "description" => "Azeri (Cyrillic) (Azerbaijan)"],
    ["code" => "be",        "description" => "Belarusian"],
    ["code" => "be-BY",     "description" => "Belarusian (Belarus)"],
    ["code" => "bg",        "description" => "Bulgarian"],
    ["code" => "bg-BG",     "description" => "Bulgarian (Bulgaria)"],
    ["code" => "bs-BA",     "description" => "Bosnian (Bosnia and Herzegovina)"],
    ["code" => "ca",        "description" => "Catalan"],
    ["code" => "ca-ES",     "description" => "Catalan (Spain)"],
    ["code" => "cs",        "description" => "Czech"],
    ["code" => "cs-CZ",     "description" => "Czech (Czech Republic)"],
    ["code" => "cy",        "description" => "Welsh"],
    ["code" => "cy-GB",     "description" => "Welsh (United Kingdom)"],
    ["code" => "da",        "description" => "Danish"],
    ["code" => "da-DK",     "description" => "Danish (Denmark)"],
    ["code" => "de",        "description" => "German"],
    ["code" => "de-AT",     "description" => "German (Austria)"],
    ["code" => "de-CH",     "description" => "German (Switzerland)"],
    ["code" => "de-DE",     "description" => "German (Germany)"],
    ["code" => "de-LI",     "description" => "German (Liechtenstein)"],
    ["code" => "de-LU",     "description" => "German (Luxembourg)"],
    ["code" => "dv",        "description" => "Divehi"],
    ["code" => "dv-MV",     "description" => "Divehi (Maldives)"],
    ["code" => "el",        "description" => "Greek"],
    ["code" => "el-GR",     "description" => "Greek (Greece)"],
    ["code" => "en",        "description" => "English"],
    ["code" => "en-AU",     "description" => "English (Australia)"],
    ["code" => "en-BZ",     "description" => "English (Belize)"],
    ["code" => "en-CA",     "description" => "English (Canada)"],
    ["code" => "en-CB",     "description" => "English (Caribbean)"],
    ["code" => "en-GB",     "description" => "English (United Kingdom)"],
    ["code" => "en-IE",     "description" => "English (Ireland)"],
    ["code" => "en-JM",     "description" => "English (Jamaica)"],
    ["code" => "en-NZ",     "description" => "English (New Zealand)"],
    ["code" => "en-PH",     "description" => "English (Republic of the Philippines)"],
    ["code" => "en-TT",     "description" => "English (Trinidad and Tobago)"],
    ["code" => "en-US",     "description" => "English (United States)"],
    ["code" => "en-ZA",     "description" => "English (South Africa)"],
    ["code" => "en-ZW",     "description" => "English (Zimbabwe)"],
    ["code" => "eo",        "description" => "Esperanto"],
    ["code" => "es",        "description" => "Spanish"],
    ["code" => "es-AR",     "description" => "Spanish (Argentina)"],
    ["code" => "es-BO",     "description" => "Spanish (Bolivia)"],
    ["code" => "es-CL",     "description" => "Spanish (Chile)"],
    ["code" => "es-CO",     "description" => "Spanish (Colombia)"],
    ["code" => "es-CR",     "description" => "Spanish (Costa Rica)"],
    ["code" => "es-DO",     "description" => "Spanish (Dominican Republic)"],
    ["code" => "es-EC",     "description" => "Spanish (Ecuador)"],
    ["code" => "es-ES",     "description" => "Spanish (Castilian)"],
    ["code" => "es-ES",     "description" => "Spanish (Spain)"],
    ["code" => "es-GT",     "description" => "Spanish (Guatemala)"],
    ["code" => "es-HN",     "description" => "Spanish (Honduras)"],
    ["code" => "es-MX",     "description" => "Spanish (Mexico)"],
    ["code" => "es-NI",     "description" => "Spanish (Nicaragua)"],
    ["code" => "es-PA",     "description" => "Spanish (Panama)"],
    ["code" => "es-PE",     "description" => "Spanish (Peru)"],
    ["code" => "es-PR",     "description" => "Spanish (Puerto Rico)"],
    ["code" => "es-PY",     "description" => "Spanish (Paraguay)"],
    ["code" => "es-SV",     "description" => "Spanish (El Salvador)"],
    ["code" => "es-UY",     "description" => "Spanish (Uruguay)"],
    ["code" => "es-VE",     "description" => "Spanish (Venezuela)"],
    ["code" => "et",        "description" => "Estonian"],
    ["code" => "et-EE",     "description" => "Estonian (Estonia)"],
    ["code" => "eu",        "description" => "Basque"],
    ["code" => "eu-ES",     "description" => "Basque (Spain)"],
    ["code" => "fa",        "description" => "Farsi"],
    ["code" => "fa-IR",     "description" => "Farsi (Iran)"],
    ["code" => "fi",        "description" => "Finnish"],
    ["code" => "fi-FI",     "description" => "Finnish (Finland)"],
    ["code" => "fo",        "description" => "Faroese"],
    ["code" => "fo-FO",     "description" => "Faroese (Faroe Islands)"],
    ["code" => "fr",        "description" => "French"],
    ["code" => "fr-BE",     "description" => "French (Belgium)"],
    ["code" => "fr-CA",     "description" => "French (Canada)"],
    ["code" => "fr-CH",     "description" => "French (Switzerland)"],
    ["code" => "fr-FR",     "description" => "French (France)"],
    ["code" => "fr-LU",     "description" => "French (Luxembourg)"],
    ["code" => "fr-MC",     "description" => "French (Principality of Monaco)"],
    ["code" => "gl",        "description" => "Galician"],
    ["code" => "gl-ES",     "description" => "Galician (Spain)"],
    ["code" => "gu",        "description" => "Gujarati"],
    ["code" => "gu-IN",     "description" => "Gujarati (India)"],
    ["code" => "he",        "description" => "Hebrew"],
    ["code" => "he-IL",     "description" => "Hebrew (Israel)"],
    ["code" => "hi",        "description" => "Hindi"],
    ["code" => "hi-IN",     "description" => "Hindi (India)"],
    ["code" => "hr",        "description" => "Croatian"],
    ["code" => "hr-BA",     "description" => "Croatian (Bosnia and Herzegovina)"],
    ["code" => "hr-HR",     "description" => "Croatian (Croatia)"],
    ["code" => "hu",        "description" => "Hungarian"],
    ["code" => "hu-HU",     "description" => "Hungarian (Hungary)"],
    ["code" => "hy",        "description" => "Armenian"],
    ["code" => "hy-AM",     "description" => "Armenian (Armenia)"],
    ["code" => "id",        "description" => "Indonesian"],
    ["code" => "id-ID",     "description" => "Indonesian (Indonesia)"],
    ["code" => "is",        "description" => "Icelandic"],
    ["code" => "is-IS",     "description" => "Icelandic (Iceland)"],
    ["code" => "it",        "description" => "Italian"],
    ["code" => "it-CH",     "description" => "Italian (Switzerland)"],
    ["code" => "it-IT",     "description" => "Italian (Italy)"],
    ["code" => "ja",        "description" => "Japanese"],
    ["code" => "ja-JP",     "description" => "Japanese (Japan)"],
    ["code" => "ka",        "description" => "Georgian"],
    ["code" => "ka-GE",     "description" => "Georgian (Georgia)"],
    ["code" => "kk",        "description" => "Kazakh"],
    ["code" => "kk-KZ",     "description" => "Kazakh (Kazakhstan)"],
    ["code" => "kn",        "description" => "Kannada"],
    ["code" => "kn-IN",     "description" => "Kannada (India)"],
    ["code" => "ko",        "description" => "Korean"],
    ["code" => "ko-KR",     "description" => "Korean (Korea)"],
    ["code" => "kok",       "description" => "Konkani"],
    ["code" => "kok-IN",    "description" => "Konkani (India)"],
    ["code" => "ky",        "description" => "Kyrgyz"],
    ["code" => "ky-KG",     "description" => "Kyrgyz (Kyrgyzstan)"],
    ["code" => "lt",        "description" => "Lithuanian"],
    ["code" => "lt-LT",     "description" => "Lithuanian (Lithuania)"],
    ["code" => "lv",        "description" => "Latvian"],
    ["code" => "lv-LV",     "description" => "Latvian (Latvia)"],
    ["code" => "mi",        "description" => "Maori"],
    ["code" => "mi-NZ",     "description" => "Maori (New Zealand)"],
    ["code" => "mk",        "description" => "FYRO Macedonian"],
    ["code" => "mk-MK",     "description" => "FYRO Macedonian (Former Yugoslav Republic of Macedonia)"],
    ["code" => "mn",        "description" => "Mongolian"],
    ["code" => "mn-MN",     "description" => "Mongolian (Mongolia)"],
    ["code" => "mr",        "description" => "Marathi"],
    ["code" => "mr-IN",     "description" => "Marathi (India)"],
    ["code" => "ms",        "description" => "Malay"],
    ["code" => "ms-BN",     "description" => "Malay (Brunei Darussalam)"],
    ["code" => "ms-MY",     "description" => "Malay (Malaysia)"],
    ["code" => "mt",        "description" => "Maltese"],
    ["code" => "mt-MT",     "description" => "Maltese (Malta)"],
    ["code" => "nb",        "description" => "Norwegian (Bokm?l)"],
    ["code" => "nb-NO",     "description" => "Norwegian (Bokm?l) (Norway)"],
    ["code" => "nl",        "description" => "Dutch"],
    ["code" => "nl-BE",     "description" => "Dutch (Belgium)"],
    ["code" => "nl-NL",     "description" => "Dutch (Netherlands)"],
    ["code" => "nn-NO",     "description" => "Norwegian (Nynorsk) (Norway)"],
    ["code" => "ns",        "description" => "Northern Sotho"],
    ["code" => "ns-ZA",     "description" => "Northern Sotho (South Africa)"],
    ["code" => "pa",        "description" => "Punjabi"],
    ["code" => "pa-IN",     "description" => "Punjabi (India)"],
    ["code" => "pl",        "description" => "Polish"],
    ["code" => "pl-PL",     "description" => "Polish (Poland)"],
    ["code" => "ps",        "description" => "Pashto"],
    ["code" => "ps-AR",     "description" => "Pashto (Afghanistan)"],
    ["code" => "pt",        "description" => "Portuguese"],
    ["code" => "pt-BR",     "description" => "Portuguese (Brazil)"],
    ["code" => "pt-PT",     "description" => "Portuguese (Portugal)"],
    ["code" => "qu",        "description" => "Quechua"],
    ["code" => "qu-BO",     "description" => "Quechua (Bolivia)"],
    ["code" => "qu-EC",     "description" => "Quechua (Ecuador)"],
    ["code" => "qu-PE",     "description" => "Quechua (Peru)"],
    ["code" => "ro",        "description" => "Romanian"],
    ["code" => "ro-RO",     "description" => "Romanian (Romania)"],
    ["code" => "ru",        "description" => "Russian"],
    ["code" => "ru-RU",     "description" => "Russian (Russia)"],
    ["code" => "sa",        "description" => "Sanskrit"],
    ["code" => "sa-IN",     "description" => "Sanskrit (India)"],
    ["code" => "se",        "description" => "Sami (Northern)"],
    ["code" => "se-FI",     "description" => "Sami (Northern) (Finland)"],
    ["code" => "se-FI",     "description" => "Sami (Skolt) (Finland)"],
    ["code" => "se-FI",     "description" => "Sami (Inari) (Finland)"],
    ["code" => "se-NO",     "description" => "Sami (Northern) (Norway)"],
    ["code" => "se-NO",     "description" => "Sami (Lule) (Norway)"],
    ["code" => "se-NO",     "description" => "Sami (Southern) (Norway)"],
    ["code" => "se-SE",     "description" => "Sami (Northern) (Sweden)"],
    ["code" => "se-SE",     "description" => "Sami (Lule) (Sweden)"],
    ["code" => "se-SE",     "description" => "Sami (Southern) (Sweden)"],
    ["code" => "sk",        "description" => "Slovak"],
    ["code" => "sk-SK",     "description" => "Slovak (Slovakia)"],
    ["code" => "sl",        "description" => "Slovenian"],
    ["code" => "sl-SI",     "description" => "Slovenian (Slovenia)"],
    ["code" => "sq",        "description" => "Albanian"],
    ["code" => "sq-AL",     "description" => "Albanian (Albania)"],
    ["code" => "sr-BA",     "description" => "Serbian (Latin) (Bosnia and Herzegovina)"],
    ["code" => "sr-BA",     "description" => "Serbian (Cyrillic) (Bosnia and Herzegovina)"],
    ["code" => "sr-SP",     "description" => "Serbian (Latin) (Serbia and Montenegro)"],
    ["code" => "sr-SP",     "description" => "Serbian (Cyrillic) (Serbia and Montenegro)"],
    ["code" => "sv",        "description" => "Swedish"],
    ["code" => "sv-FI",     "description" => "Swedish (Finland)"],
    ["code" => "sv-SE",     "description" => "Swedish (Sweden)"],
    ["code" => "sw",        "description" => "Swahili"],
    ["code" => "sw-KE",     "description" => "Swahili (Kenya)"],
    ["code" => "syr",       "description" => "Syriac"],
    ["code" => "syr-SY",    "description" => "Syriac (Syria)"],
    ["code" => "ta",        "description" => "Tamil"],
    ["code" => "ta-IN",     "description" => "Tamil (India)"],
    ["code" => "te",        "description" => "Telugu"],
    ["code" => "te-IN",     "description" => "Telugu (India)"],
    ["code" => "th",        "description" => "Thai"],
    ["code" => "th-TH",     "description" => "Thai (Thailand)"],
    ["code" => "tl",        "description" => "Tagalog"],
    ["code" => "tl-PH",     "description" => "Tagalog (Philippines)"],
    ["code" => "tn",        "description" => "Tswana"],
    ["code" => "tn-ZA",     "description" => "Tswana (South Africa)"],
    ["code" => "tr",        "description" => "Turkish"],
    ["code" => "tr-TR",     "description" => "Turkish (Turkey)"],
    ["code" => "tt",        "description" => "Tatar"],
    ["code" => "tt-RU",     "description" => "Tatar (Russia)"],
    ["code" => "ts",        "description" => "Tsonga"],
    ["code" => "uk",        "description" => "Ukrainian"],
    ["code" => "uk-UA",     "description" => "Ukrainian (Ukraine)"],
    ["code" => "ur",        "description" => "Urdu"],
    ["code" => "ur-PK",     "description" => "Urdu (Islamic Republic of Pakistan)"],
    ["code" => "uz",        "description" => "Uzbek (Latin)"],
    ["code" => "uz-UZ",     "description" => "Uzbek (Latin) (Uzbekistan)"],
    ["code" => "uz-UZ",     "description" => "Uzbek (Cyrillic) (Uzbekistan)"],
    ["code" => "vi",        "description" => "Vietnamese"],
    ["code" => "vi-VN",     "description" => "Vietnamese (Viet Nam)"],
    ["code" => "xh",        "description" => "Xhosa"],
    ["code" => "xh-ZA",     "description" => "Xhosa (South Africa)"],
    ["code" => "zh",        "description" => "Chinese"],
    ["code" => "zh-CN",     "description" => "Chinese (China)"],
    ["code" => "zh-HK",     "description" => "Chinese (Hong Kong)"],
    ["code" => "zh-MO",     "description" => "Chinese (Macau)"],
    ["code" => "zh-SG",     "description" => "Chinese (Singapore)"],
    ["code" => "zh-TW",     "description" => "Chinese (Taiwan)"],
    ["code" => "zu",        "description" => "Zulu"],
    ["code" => "zu-ZA",     "description" => "Zulu (South Africa)"]
];